# Test workflows for Dockstore WES
version: 1.2
workflows:

        
   -  name: multi-descriptor-no-input
      subclass: WDL
      primaryDescriptorPath: workflows/wdl/w2/multiDescriptorNoInput.wdl
